# Generated by Django 2.0.4 on 2018-04-30 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Audiencia',
                'verbose_name_plural': 'Audiencias',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True, verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, unique=True, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de contenido',
                'verbose_name_plural': 'Tipos de contenidos',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, verbose_name='Ubicación del sitio')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del servicio')),
                ('description', models.CharField(max_length=1000, verbose_name='Descripción')),
                ('es_externo', models.BooleanField(default=False, verbose_name='Es externo')),
            ],
            options={
                'verbose_name': 'Servicio Integrado',
                'verbose_name_plural': 'Servicios Integrados',
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del proveedor')),
                ('description', models.CharField(max_length=1000, verbose_name='Descripción del proveedor')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('domain', models.CharField(max_length=100, unique=True, verbose_name='Dominio')),
                ('url_home', models.CharField(max_length=200, unique=True, verbose_name='Url')),
                ('description', models.CharField(max_length=1000, verbose_name='Descripción')),
                ('unit', models.CharField(max_length=100, verbose_name='Unidad responsable')),
                ('contact', models.CharField(max_length=200, verbose_name='Contacto')),
                ('tech_resp', models.CharField(max_length=200, verbose_name='Responsable técnico')),
                ('update_resp', models.CharField(max_length=200, verbose_name='Responsable actualización')),
                ('creation_date', models.DateTimeField(verbose_name='Fecha creación')),
                ('last_update_date', models.DateTimeField(verbose_name='Fecha actualización')),
                ('contract_end_date', models.DateTimeField(verbose_name='Fecha fin del contrato')),
                ('size', models.IntegerField(verbose_name='Tamaño (#páginas)')),
                ('visits', models.IntegerField(verbose_name='Visitas')),
                ('analytics', models.CharField(max_length=100, verbose_name='Analytics')),
                ('authentication', models.BooleanField(default=True, verbose_name='Tiene autenticación')),
                ('design', models.CharField(max_length=1000, verbose_name='Diseño')),
                ('additional_info', models.CharField(max_length=1000, verbose_name='Observaciones')),
                ('image', models.CharField(max_length=1000, verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Sitio',
                'verbose_name_plural': 'Sitios',
            },
        ),
        migrations.CreateModel(
            name='SiteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, unique=True, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de sitio',
                'verbose_name_plural': 'Tipos de sitio',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100, unique=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('version', models.CharField(max_length=100, verbose_name='Versión')),
            ],
            options={
                'verbose_name': 'Tecnología',
                'verbose_name_plural': 'Tecnologías',
            },
        ),
        migrations.CreateModel(
            name='TechnologyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Tipo de tecnología',
                'verbose_name_plural': 'Tipos de tecnologías',
            },
        ),
        migrations.AddField(
            model_name='technology',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='websites.TechnologyType', verbose_name='Tipo de tecnología'),
        ),
        migrations.AddField(
            model_name='site',
            name='Technology',
            field=models.ManyToManyField(blank=True, null=True, to='websites.Technology', verbose_name='Tecnologías'),
        ),
        migrations.AddField(
            model_name='site',
            name='audiences',
            field=models.ManyToManyField(blank=True, null=True, to='websites.Audience', verbose_name='Audiencias'),
        ),
        migrations.AddField(
            model_name='site',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='websites.Category', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='site',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='websites.ContentType', verbose_name='Tipo de contenido'),
        ),
        migrations.AddField(
            model_name='site',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='developer', to='websites.ServiceProvider', verbose_name='Empresa desarrolladora'),
        ),
        migrations.AddField(
            model_name='site',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='websites.Location', verbose_name='Ubicación sitio desplegado'),
        ),
        migrations.AddField(
            model_name='site',
            name='maintainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='maintainer', to='websites.ServiceProvider', verbose_name='Empresa mantenimiento'),
        ),
        migrations.AddField(
            model_name='site',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, to='websites.Service', verbose_name='Servicios'),
        ),
        migrations.AddField(
            model_name='site',
            name='site_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='websites.SiteType', verbose_name='Tipo de sitio'),
        ),
        migrations.AddField(
            model_name='site',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='websites.State', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='service',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='websites.ServiceProvider', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='location',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='websites.ServiceProvider', verbose_name='Proveedor'),
        ),
        migrations.AlterUniqueTogether(
            name='site',
            unique_together={('name', 'domain', 'url_home')},
        ),
    ]
